# **Numpy**

In [9]:
import numpy as np

# Create 1D array
arr = np.arange(5, 25)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(25, 45)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

1D Array: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
4x5 Matrix:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Mean: 14.5
Median: 14.5
Standard Deviation: 5.766281297335398
Addition: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]
Multiplication: [ 125  156  189  224  261  300  341  384  429  476  525  576  629  684
  741  800  861  924  989 1056]
